import mods.itemstages.ItemStages;

ItemStages.restrict(<item:appliedenergistics2:facade>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_covered_cable>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_covered_dense_cable>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_dust>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_glass_cable>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_pearl>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_slab>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_smart_cable>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_smart_dense_cable>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:128_cubed_spatial_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16_cubed_spatial_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16_cubed_spatial_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16k_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16k_crafting_storage>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16k_fluid_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16k_fluid_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16k_portable_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:16k_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:1k_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:1k_crafting_storage>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:1k_fluid_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:1k_fluid_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:1k_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:2_cubed_spatial_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:2_cubed_spatial_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:4k_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:4k_crafting_storage>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:4k_fluid_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:4k_fluid_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:4k_portable_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:4k_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:64k_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:64k_crafting_storage>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:64k_fluid_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:64k_fluid_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:64k_portable_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:64k_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fe_p2p_tunnel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_p2p_tunnel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:me_p2p_tunnel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:item_p2p_tunnel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:light_p2p_tunnel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:redstone_p2p_tunnel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:speed_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:basic_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:advanced_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fuzzy_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:inverter_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:capacity_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:crafting_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:sky_compass>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:sky_dust>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_block>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_brick>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_brick_slab>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_brick_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_brick_wall>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_chest>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_slab>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_small_brick>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_small_brick_slab>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_small_brick_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_small_brick_wall>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:sky_stone_wall>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_axe>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_crystal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_cutting_knife>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_hoe>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_pickaxe>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_shovel>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_quartz_sword>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:chiseled_quartz_block>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:chiseled_quartz_slab>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:chiseled_quartz_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:chiseled_quartz_wall>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:purified_certus_quartz_crystal>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_block>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quartz_fiber>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_fixture>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quartz_glass>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quartz_growth_accelerator>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_ore>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_pillar>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_pillar_slab>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_pillar_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_pillar_wall>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_slab>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_stairs>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quartz_vibrant_glass>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:quartz_wall>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:logic_processor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:logic_processor_press>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:engineering_processor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:engineering_processor_press>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:calculation_processor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:calculation_processor_press>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:crafting_monitor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:dark_monitor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:semi_dark_monitor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:monitor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:crafting_terminal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:export_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_export_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_import_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:import_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:storage_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:cell_workbench>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:creative_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:empty_storage_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:energy_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:portable_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:view_cell>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:charged_quartz_ore>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:smooth_sky_stone_block>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_block>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:smooth_sky_stone_chest>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:inscriber>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:wireless_access_point>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:charger>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:chest>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:drive>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:controller>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:spatial_io_port>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:spatial_pylon>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quantum_link>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quantum_ring>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:security_station>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:tiny_tnt>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:interface>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_interface>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:io_port>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:condenser>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:vibration_chamber>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:creative_energy_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:dense_energy_cell>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:crafting_unit>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:energy_acceptor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:crafting_accelerator>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:molecular_assembler>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:light_detector>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:smooth_sky_stone_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:fluix_stairs>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:fluix_wall>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:smooth_sky_stone_wall>, "appliedenergistics2");
// ItemStages.restrict(<item:appliedenergistics2:smooth_sky_stone_slab>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:spatial_anchor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:128_cubed_spatial_cell_component>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:silicon>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:silicon_press>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:name_press>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:printed_calculation_processor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:printed_engineering_processor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:printed_logic_processor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:printed_silicon>, "appliedenergistics2");
//ItemStages.restrict(<item:appliedenergistics2:purified_nether_quartz_crystal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:purified_fluix_crystal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:redstone_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:ender_dust>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:flour>, "appliedenergistics2");
//ItemStages.restrict(<item:appliedenergistics2:certus_quartz_dust>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:matter_ball>, "appliedenergistics2");
//ItemStages.restrict(<item:appliedenergistics2:charged_certus_quartz_crystal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_crystal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:wireless_receiver>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:wireless_booster>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:annihilation_core>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:formation_core>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:singularity>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:quantum_entangled_singularity>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:blank_pattern>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:entropy_manipulator>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:wireless_terminal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:charged_staff>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:matter_cannon>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:color_applicator>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:biometric_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:memory_card>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:network_tool>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:certus_crystal_seed>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluix_crystal_seed>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:encoded_pattern>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:toggle_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:inverted_toggle_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:cable_anchor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_storage_bus>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:level_emitter>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_level_emitter>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_formation_plane>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:formation_plane>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_annihilation_plane>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:identity_annihilation_plane>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:annihilation_plane>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:pattern_terminal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:terminal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:storage_monitor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:conversion_monitor>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:cable_interface>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:cable_fluid_interface>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:interface_terminal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:fluid_terminal>, "appliedenergistics2");
ItemStages.restrict(<item:appliedenergistics2:cable_energy_acceptor>, "appliedenergistics2");