import mods.itemstages.ItemStages;

// ItemStages.restrict(<item:atum:limestone>, "atum");
ItemStages.restrict(<item:atum:limestone_axe>, "atum");
ItemStages.restrict(<item:atum:limestone_furnace>, "atum");
// ItemStages.restrict(<item:atum:limestone_gravel>, "atum");
ItemStages.restrict(<item:atum:limestone_hoe>, "atum");
ItemStages.restrict(<item:atum:limestone_large_slab>, "atum");
ItemStages.restrict(<item:atum:limestone_pickaxe>, "atum");
ItemStages.restrict(<item:atum:limestone_pressure_plate>, "atum");
ItemStages.restrict(<item:atum:limestone_shovel>, "atum");
ItemStages.restrict(<item:atum:limestone_slab>, "atum");
ItemStages.restrict(<item:atum:limestone_small_slab>, "atum");
ItemStages.restrict(<item:atum:limestone_sword>, "atum");
ItemStages.restrict(<item:atum:limestone_torch>, "atum");
ItemStages.restrict(<item:atum:limestone_torch_unlit>, "atum");
ItemStages.restrict(<item:atum:limestone_wall>, "atum");

ItemStages.restrict(<item:atum:relic_diamond_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_diamond_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_diamond_idol>, "atum");
ItemStages.restrict(<item:atum:relic_diamond_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_diamond_ring>, "atum");
ItemStages.restrict(<item:atum:relic_dirty_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_dirty_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_dirty_idol>, "atum");
ItemStages.restrict(<item:atum:relic_dirty_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_dirty_ring>, "atum");
ItemStages.restrict(<item:atum:relic_emerald_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_emerald_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_emerald_idol>, "atum");
ItemStages.restrict(<item:atum:relic_emerald_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_emerald_ring>, "atum");
ItemStages.restrict(<item:atum:relic_gold_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_gold_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_gold_idol>, "atum");
ItemStages.restrict(<item:atum:relic_gold_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_gold_ring>, "atum");
// ItemStages.restrict(<item:atum:relic_ore>, "atum");
ItemStages.restrict(<item:atum:relic_ruby_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_ruby_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_ruby_idol>, "atum");
ItemStages.restrict(<item:atum:relic_ruby_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_ruby_ring>, "atum");
ItemStages.restrict(<item:atum:relic_sapphire_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_sapphire_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_sapphire_idol>, "atum");
ItemStages.restrict(<item:atum:relic_sapphire_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_sapphire_ring>, "atum");
ItemStages.restrict(<item:atum:relic_silver_bracelet>, "atum");
ItemStages.restrict(<item:atum:relic_silver_brooch>, "atum");
ItemStages.restrict(<item:atum:relic_silver_idol>, "atum");
ItemStages.restrict(<item:atum:relic_silver_necklace>, "atum");
ItemStages.restrict(<item:atum:relic_silver_ring>, "atum");



ItemStages.restrict(<item:atum:feet_of_atem>, "atum");
ItemStages.restrict(<item:atum:feet_of_ra>, "atum");
ItemStages.restrict(<item:atum:bone_ore>, "atum");
ItemStages.restrict(<item:atum:coal_ore>, "atum");
ItemStages.restrict(<item:atum:diamond_ore>, "atum");
ItemStages.restrict(<item:atum:emerald_ore>, "atum");
ItemStages.restrict(<item:atum:gold_ore>, "atum");
ItemStages.restrict(<item:atum:iron_ore>, "atum");
ItemStages.restrict(<item:atum:lapis_ore>, "atum");
ItemStages.restrict(<item:atum:nebu_ore>, "atum");
ItemStages.restrict(<item:atum:redstone_ore>, "atum");
ItemStages.restrict(<item:atum:sand>, "atum");
// ItemStages.restrict(<item:atum:sand_layer>, "atum");
ItemStages.restrict(<item:atum:tar_trap>, "atum");
ItemStages.restrict(<item:atum:smoke_trap>, "atum");
ItemStages.restrict(<item:atum:poison_trap>, "atum");
ItemStages.restrict(<item:atum:burning_trap>, "atum");
ItemStages.restrict(<item:atum:arrow_trap>, "atum");
ItemStages.restrict(<item:atum:gebs_might>, "atum");
ItemStages.restrict(<item:atum:gebs_toil>, "atum");
ItemStages.restrict(<item:atum:gebs_undoing>, "atum");
ItemStages.restrict(<item:atum:nebu_block>, "atum");
// ItemStages.restrict(<item:atum:nebu_chain>, "atum");
// ItemStages.restrict(<item:atum:nebu_curio_display>, "atum");
ItemStages.restrict(<item:atum:nebu_drop>, "atum");
ItemStages.restrict(<item:atum:nebu_hammer>, "atum");
ItemStages.restrict(<item:atum:nebu_ingot>, "atum");
// ItemStages.restrict(<item:atum:nebu_lantern>, "atum");
// ItemStages.restrict(<item:atum:nebu_torch>, "atum");
// ItemStages.restrict(<item:atum:nebu_torch_unlit>, "atum");
ItemStages.restrict(<item:atum:nepthys_banishing>, "atum");
ItemStages.restrict(<item:atum:stoneguard_club>, "atum");
ItemStages.restrict(<item:atum:stoneguard_greatsword>, "atum");
ItemStages.restrict(<item:atum:stoneguard_khopesh>, "atum");
ItemStages.restrict(<item:atum:stoneguard_shield>, "atum");
ItemStages.restrict(<item:atum:stoneguard_sword>, "atum");
ItemStages.restrict(<item:atum:ra_stone>, "atum");
ItemStages.restrict(<item:atum:legs_of_atem>, "atum");
ItemStages.restrict(<item:atum:legs_of_ra>, "atum");
ItemStages.restrict(<item:atum:body_of_atem>, "atum");
ItemStages.restrict(<item:atum:body_of_ra>, "atum");
ItemStages.restrict(<item:atum:godforged_block>, "atum");
ItemStages.restrict(<item:atum:anput_godforged_block>, "atum");
ItemStages.restrict(<item:atum:anubis_godforged_block>, "atum");
ItemStages.restrict(<item:atum:atem_godforged_block>, "atum");
ItemStages.restrict(<item:atum:geb_godforged_block>, "atum");
// ItemStages.restrict(<item:atum:emmer_block>, "atum");
// ItemStages.restrict(<item:atum:oasis_grass>, "atum");
// ItemStages.restrict(<item:atum:dry_grass>, "atum");
// ItemStages.restrict(<item:atum:tall_dry_grass>, "atum");
// ItemStages.restrict(<item:atum:shrub>, "atum");
// ItemStages.restrict(<item:atum:weed>, "atum");
// ItemStages.restrict(<item:atum:ophidian_tongue>, "atum");
// ItemStages.restrict(<item:atum:fertile_soil>, "atum");
// ItemStages.restrict(<item:atum:fertile_soil_tilled>, "atum");
// ItemStages.restrict(<item:atum:fertile_soil_path>, "atum");
// ItemStages.restrict(<item:atum:strange_sand_path>, "atum");
ItemStages.restrict(<item:atum:spinning_wheel>, "atum");
ItemStages.restrict(<item:atum:kiln>, "atum");
ItemStages.restrict(<item:atum:godforge>, "atum");
// ItemStages.restrict(<item:atum:quandary_block>, "atum");
ItemStages.restrict(<item:atum:glassblower_furnace>, "atum");
// ItemStages.restrict(<item:atum:acacia_curio_display>, "atum");
ItemStages.restrict(<item:atum:sarcophagus>, "atum");
ItemStages.restrict(<item:atum:khnumite_raw>, "atum");
ItemStages.restrict(<item:atum:dirty_bone_block>, "atum");
// ItemStages.restrict(<item:atum:dirty_bone_slab>, "atum");
// ItemStages.restrict(<item:atum:bone_ladder>, "atum");
// ItemStages.restrict(<item:atum:bone_torch>, "atum");
ItemStages.restrict(<item:atum:marl>, "atum");
ItemStages.restrict(<item:atum:khnumite_block>, "atum");
// ItemStages.restrict(<item:atum:khnumite_face>, "atum");
// ItemStages.restrict(<item:atum:smooth_stairs>, "atum");
// ItemStages.restrict(<item:atum:small_stairs>, "atum");
// ItemStages.restrict(<item:atum:large_stairs>, "atum");
// ItemStages.restrict(<item:atum:carved_stairs>, "atum");
// ItemStages.restrict(<item:atum:small_wall>, "atum");
// ItemStages.restrict(<item:atum:large_wall>, "atum");
// ItemStages.restrict(<item:atum:carved_wall>, "atum");
// ItemStages.restrict(<item:atum:crystal_glass>, "atum");
// ItemStages.restrict(<item:atum:crystal_glass_pane>, "atum");
// ItemStages.restrict(<item:atum:palm_framed_crystal_glass>, "atum");
// ItemStages.restrict(<item:atum:deadwood_framed_crystal_glass>, "atum");
// ItemStages.restrict(<item:atum:palm_framed_crystal_glass_pane>, "atum");
// ItemStages.restrict(<item:atum:deadwood_framed_crystal_glass_pane>, "atum");
// ItemStages.restrict(<item:atum:stripped_palm_log>, "atum");
// ItemStages.restrict(<item:atum:stripped_palm_wood>, "atum");
// ItemStages.restrict(<item:atum:stripped_deadwood_log>, "atum");
// ItemStages.restrict(<item:atum:stripped_deadwood_wood>, "atum");
// ItemStages.restrict(<item:atum:dusty_bone_stick>, "atum");
ItemStages.restrict(<item:atum:khnumite>, "atum");
ItemStages.restrict(<item:atum:coin_dirty>, "atum");
ItemStages.restrict(<item:atum:efreet_heart>, "atum");
ItemStages.restrict(<item:atum:scarab>, "atum");
ItemStages.restrict(<item:atum:idol_of_labor>, "atum");
ItemStages.restrict(<item:atum:short_bow>, "atum");
ItemStages.restrict(<item:atum:dagger_poison>, "atum");
ItemStages.restrict(<item:atum:brigand_shield>, "atum");
ItemStages.restrict(<item:atum:osiris_blessing>, "atum");
ItemStages.restrict(<item:atum:osiris_mercy>, "atum");
ItemStages.restrict(<item:atum:halo_of_ra>, "atum");
ItemStages.restrict(<item:atum:ras_fury>, "atum");
ItemStages.restrict(<item:atum:ras_step>, "atum");
ItemStages.restrict(<item:atum:seths_sting>, "atum");
ItemStages.restrict(<item:atum:seths_venom>, "atum");
ItemStages.restrict(<item:atum:shus_breath>, "atum");
ItemStages.restrict(<item:atum:shus_exile>, "atum");
ItemStages.restrict(<item:atum:anubis_wrath>, "atum");
ItemStages.restrict(<item:atum:shus_swiftness>, "atum");
ItemStages.restrict(<item:atum:tefnuts_call>, "atum");
ItemStages.restrict(<item:atum:tefnuts_rain>, "atum");
ItemStages.restrict(<item:atum:mummy_helmet>, "atum");
ItemStages.restrict(<item:atum:anputs_grounding>, "atum");
ItemStages.restrict(<item:atum:anputs_hunger>, "atum");
ItemStages.restrict(<item:atum:horus_ascension>, "atum");
ItemStages.restrict(<item:atum:mummy_boots>, "atum");
ItemStages.restrict(<item:atum:mummy_chest>, "atum");
// ItemStages.restrict(<item:atum:quail>, "atum");
// ItemStages.restrict(<item:atum:quail_cooked>, "atum");
ItemStages.restrict(<item:atum:mummy_legs>, "atum");
ItemStages.restrict(<item:atum:wanderer_boots>, "atum");
ItemStages.restrict(<item:atum:wanderer_chest>, "atum");
ItemStages.restrict(<item:atum:wanderer_helmet>, "atum");
ItemStages.restrict(<item:atum:wanderer_legs>, "atum");
ItemStages.restrict(<item:atum:horus_soaring>, "atum");
// ItemStages.restrict(<item:atum:fish_forsaken>, "atum");
// ItemStages.restrict(<item:atum:fish_jeweled>, "atum");
// ItemStages.restrict(<item:atum:fish_mummified>, "atum");
// ItemStages.restrict(<item:atum:fish_skeletal>, "atum");
// ItemStages.restrict(<item:atum:emmer>, "atum");
// ItemStages.restrict(<item:atum:emmer_bread>, "atum");
// ItemStages.restrict(<item:atum:emmer_dough>, "atum");
// ItemStages.restrict(<item:atum:emmer_flour>, "atum");
// ItemStages.restrict(<item:atum:emmer_seeds>, "atum");
// ItemStages.restrict(<item:atum:emmer_wheat>, "atum");
ItemStages.restrict(<item:atum:atems_bounty>, "atum");
ItemStages.restrict(<item:atum:atems_homecoming>, "atum");
ItemStages.restrict(<item:atum:atems_protection>, "atum");
ItemStages.restrict(<item:atum:atems_will>, "atum");
// ItemStages.restrict(<item:atum:papyrus_plant>, "atum");
// ItemStages.restrict(<item:atum:crunchy_scarab>, "atum");
ItemStages.restrict(<item:atum:ectoplasm>, "atum");
ItemStages.restrict(<item:atum:mandibles>, "atum");
ItemStages.restrict(<item:atum:dusty_bone>, "atum");
ItemStages.restrict(<item:atum:wolf_pelt>, "atum");
// ItemStages.restrict(<item:atum:fertile_soil_pile>, "atum");
// ItemStages.restrict(<item:atum:glistering_date>, "atum");
// ItemStages.restrict(<item:atum:date>, "atum");
// ItemStages.restrict(<item:atum:camel_cooked>, "atum");
// ItemStages.restrict(<item:atum:camel>, "atum");
ItemStages.restrict(<item:atum:ptahs_decadence>, "atum");
ItemStages.restrict(<item:atum:scroll>, "atum");
// ItemStages.restrict(<item:atum:ophidian_tongue_flower>, "atum");
// ItemStages.restrict(<item:atum:flax_seeds>, "atum");
ItemStages.restrict(<item:atum:montus_blast>, "atum");
ItemStages.restrict(<item:atum:isis_healing>, "atum");
ItemStages.restrict(<item:atum:isis_division>, "atum");
ItemStages.restrict(<item:atum:nuits_ire>, "atum");
ItemStages.restrict(<item:atum:nuits_quarter>, "atum");
ItemStages.restrict(<item:atum:nuits_vanishing>, "atum");
// ItemStages.restrict(<item:atum:flax>, "atum");
// ItemStages.restrict(<item:atum:cloth_scrap>, "atum");