#This file stores configuration options for Oculus, such as the currently active shaderpack
#Thu Jun 25 12:58:42 MSK 2026
enableDebugOptions=false
colorSpace=SRGB
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=ComplementaryReimagined_r5.7.1.zip
